### ISSUE TITLE
Mail subject / Mail content

### ISSUE THREAD

**Issue by peterryck** [alramlechner/CommonLogicNodes#2]
Hi, would it be possible to change the module so that you can modify the subject (preferrably with a text string coming from another node), as well as the content of the mail ?

**Comment by alramlechner** [comment]
hi peterryck,

sorry for the late response. sounds reasonable .. will try to make it in the next few days ...

Alram

**Comment by peterryck** [comment]
Hi Alram,

I found another issue with the logic node.  It works well in simulation mode (I do receive an email), but when I put it into production, nothing seems to happen (I don’t receive an email).   Is there anything that you could think of ?

P.S.        As for the request below, I’m willing to donate something (I don’t know if this is appropriate on Github, but a working version of your solution would really help me).

Best regards,

Peter

**Comment by alramlechner** [comment]
i have created a new build, where subject + mailbody can be configured. try: https://nas.lechners.name:5001/fsdownload/lBaUQQngC/X1Nodes
your donation is, that you run + test it on X1. i have tried this new version in GPA only. (i have currently not the possibility to run it on an X1)
regarding it is running in GPA only - not on X1: this can have many reasons. network related, the trigger doesn't fire. difficult to analyze from outside.
try to scan the embedded website of the X1 and fetch analysis logs. might help ...
Alram

**Comment by peterryck** [comment]
Hi Alram,

I’ve tested the new node.

In GPA : it works fine
In GPA when moved to the X1 environment (but before uploading it) : it shows the following issue

[cid:image001.png@01D63385.E7CAE8B0]

In X1 (after uploading) : strange behaviour of the X1, most probably due to the memory issues

I tried again with your previous version, and that doesn’t show that behaviour.

Best regards,

Peter

**Comment by alramlechner** [comment]
try alram_lechner_gmx_at.logic.Mail-0.0.14.zip - the upgrade to MailKit 2.6 let the node to fail on X1.

**Comment by peterryck** [comment]
It seems to work !  I’ll do some more testing tomorrow, but the first tests are OK.

I’m wondering if it would take a great deal of work to allow some text inputs that can be used in the subject (with a placeholder such as %input1%) or in the body text ?

Anyway, thanks a lot for the work you have done !

Peter

**Comment by alramlechner** [comment]
thanks for the feedback.
regarding your text format: i have build new version alram_lechner_gmx_at.logic.Mail-0.0.16.zip, that allows for subject + mailtext being an input from other nodes.
take a look at the text formater node provided by hyman: https://knx-user-forum.de/forum/supportforen/gira-logik-sdk/1334960-neuer-logikbaustein-textformatierer
in combination with that node you should be able to solve your issue.
i'll close this issue for now.
Alram
